
import 'package:flutter/material.dart';
import 'package:youtube_player_flutter/youtube_player_flutter.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart';




class VideoScreen2 extends StatefulWidget {

  final String id;
  VideoScreen2({required this.id});


  @override
  _VideoScreen2State createState() => _VideoScreen2State();
}


class _VideoScreen2State extends State<VideoScreen2> {
  final _controller = TextEditingController();
  String caption = "Youtube Caption Will be Displayed Here";


  Future<void> getCaption(String id) async {

    final yt = YoutubeExplode();

    var manifest = await yt.videos.closedCaptions.getManifest(widget.id);
    var trackInfo = manifest.getByLanguage('en', autoGenerated: true);
    var track = await yt.videos.closedCaptions.get(trackInfo.first);
    // print(track.captions);

    var tt = trackInfo.iterator;
    if (trackInfo != null) {
      while (tt.moveNext()) {
        var track = await yt.videos.closedCaptions.get(tt.current);
        // captions = track.toJson();
        for (var e in track.captions) {
          print(e.text);
          //print(e.offset); //time offset
          //e.end Time at which this caption ends being displayed.
          // e.offset Time at which this caption starts being displayed.
        }
      }
    }
    // print(track.captions.runtimeType);
    yt.close();
  }

  @override


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        children: [

          const SizedBox(height: 5),
          MaterialButton(
            minWidth: double.infinity,
            height: 30,
            onPressed: () {
              setState(() {
                getCaption(widget.id);
               caption = _controller.text;
              });


            },
            color: const Color(0xff0095FF),
            shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(50)),
            child: const Text(
              "Get Caption",
              style: TextStyle(
                  color: Colors.white,
                  fontWeight: FontWeight.w600,
                  fontSize: 18),
            ),
          ),


          Container(
            width: 300,
            height: 200,
            color: Colors.grey,
            child: SingleChildScrollView(
              scrollDirection: Axis.vertical,
              //.horizontal
              padding: const EdgeInsets.fromLTRB(10.0, 10.0, 10.0, 10.0),
              child:  Text(caption
                ,style: TextStyle(
                  fontSize: 16.0, color: Colors.white,
                ),
              ),
            ),
          ),

        ],

      ),

    );
  }
}